package:
  name: pyarrow
  version: {{ ARROW_VERSION }}

source:
  path: ../../../

build:
  number: 0
  skip: true  # [win32]
  skip: true  # [win and py<35]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - setuptools_scm
    - cython
    - cmake
    - numpy 1.10.*  # [not (win and py>=36)]
    - numpy 1.12.*  # [win and py>=36]
    - six
    - arrow-cpp 0.9.0
    - parquet-cpp 1.4.0

  run:
    - python
    - setuptools
    - numpy >=1.10  # [not (win and py>=36)]
    - numpy >=1.12  # [win and py>=36]
    - pandas
    - six
    - arrow-cpp {{ ARROW_VERSION }}
    - parquet-cpp 1.4.0
    - futures  # [py27]

test:
  imports:
    - pyarrow
    - pyarrow.parquet
    - pyarrow.plasma  # [unix]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
