os: Visual Studio 2015

environment:
  matrix:
    - GENERATOR: Visual Studio 14 2015 Win64
      NUMPY: "1.13"
      PYTHON: "3.5"
      ARCH: "64"
    - GENERATOR: Visual Studio 14 2015 Win64
      NUMPY: "1.13"
      PYTHON: "3.6"
      ARCH: "64"
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_63_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_63_0\lib64-msvc-14.0
  pyarrow_version: 0.9.0
  pyarrow_ref: 7b2c79765cf92760e1f8cca079159d9613b86412
  parquet_cpp_ref: apache-parquet-cpp-1.4.0
  ARROW_SRC=C:\apache-arrow

init:
  - set MINICONDA=C:\Miniconda35-x64
  - set PATH=%MINICONDA%;%MINICONDA%/Scripts;%MINICONDA%/Library/bin;%PATH%

build_script:
  - mkdir wheels
  - git clone -b {ARROW_BRANCH} {ARROW_REPO} %ARROW_SRC% || exit /B
  - call %ARROW_SRC%\cd\win-wheel\python-wheels-windows.bat

after_build:
  xcopy %ARROW_SRC%\python\dist\* wheels\

artifacts:
  - path: wheels\*.whl
